name: cropmet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
   
  http: any #  API calls
  internet_connection_checker_plus: any # check internet connection
  geolocator: any # location access
  intl: any #  date formatting
  permission_handler: any # user permissions
  flutter_launcher_icons: any # to change app icon
  material_design_icons_flutter: any  # for icons
  ionicons: any #for icons
  weather_icons: any # for weather icons
  font_awesome_flutter: any # for modren icons
  url_launcher: any # for urls
  shared_preferences: any #for local storage
  image_network: any   # for images/icons
  google_nav_bar: any # for nav bar
  hive_flutter: any # for local storage
  hive: any # for local storage
  path_provider: any # for local storage



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/cropmet.png"

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/city_list_filtered.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
